#This script takes as input the table generated by the script 'rbp_enrichment.R', and creates the two frames of figure 7

library(ggpubr)

source('get_fdr_prob.R')


enrich.mat=read.table('rbp_enrichment_sarscov2.txt',header=TRUE)

enrich.mat=cbind(enrich.mat,p.adjust(as.numeric(enrich.mat$P.Value.Down),method='BH'))

colnames(enrich.mat)[ncol(enrich.mat)]='p.down.adjusted'

enrich.mat=cbind(enrich.mat,p.adjust(as.numeric(enrich.mat$P.Value.Up),method='BH'))

colnames(enrich.mat)[ncol(enrich.mat)]='p.up.adjusted'

rbp.tab=read.csv('RBP_id_encoding.csv',header=FALSE)

colnames(rbp.tab)=c('rbp.num','RBP')

enrich.mat=merge(enrich.mat,rbp.tab,by.x='RBP',by.y='rbp.num')

enrich.mat=enrich.mat[,-1]

colnames(enrich.mat)[ncol(enrich.mat)]='RBP'

all.datasets=c(
  "SRP040070_3","SRP040070_7","SRP040070_9",
  "SRP227272_38",'SRP279203_72','SRP294125_74',"SRP078309_53","SRP178454_50","SRP186406_51","SRP216763_55","SRP222569_54","SRP251704_52",
  "SRP273785_56",'SRP284977_76','SRP284977_77')

betacoronas=c("SRP040070_3","SRP040070_7","SRP040070_9","SRP227272_38",'SRP279203_72','SRP294125_74','SRP284977_76','SRP284977_77')

sum(enrich.mat$Dataset[enrich.mat$p.down.adjusted<=0.05] %in% betacoronas)

table(enrich.mat$Dataset[enrich.mat$p.down.adjusted<=0.05])

sum(!enrich.mat$Dataset[enrich.mat$p.down.adjusted<=0.05] %in% betacoronas)

table(enrich.mat$Dataset)

sum(enrich.mat$Dataset[enrich.mat$p.up.adjusted<=0.05] %in% betacoronas)

table(enrich.mat$Dataset[enrich.mat$p.up.adjusted<=0.05])

sum(!enrich.mat$Dataset[enrich.mat$p.up.adjusted<=0.05] %in% betacoronas)

df=data.frame(matrix(ncol=3,nrow=0))

for (dataset in all.datasets)
{
  
  num.up.rbp=sum(enrich.mat$Dataset[enrich.mat$p.up.adjusted<=0.05]==dataset)
  
  num.down.rbp=sum(enrich.mat$Dataset[enrich.mat$p.down.adjusted<=0.05]==dataset)
  
  res=read.table(paste0('HBA-DEALS-covid19_output/',dataset,'.txt'),header=TRUE)
  
  thresh=get.fdr.prob(res)
  
  ds.isoforms=res$Isoform[res$Isoform!='Expression' & res$P<=thresh[[2]]]
  
  df=rbind(df,c(dataset,num.up.rbp/length(ds.isoforms),num.down.rbp/(sum(res$Isoform!='Expression')-length(ds.isoforms))))
  
}

colnames(df)=c('dataset','up.norm','down.norm')

df1=data.frame(enrich.score=as.numeric(df$up.norm),type=ifelse(df$dataset %in% betacoronas,'Coronavirus','Other'))

ggboxplot(data = df1,x = 'type',y = 'enrich.score',palette = 'npg',fill = 'type',add='jitter',shape='type')+
  stat_compare_means(aes(group = type),vjust=2)

wilcox.test(as.numeric(df$up.norm[df$dataset %in% betacoronas]),as.numeric(df$up.norm[!df$dataset %in% betacoronas]),paired = FALSE)

df2=data.frame(deplete.score=as.numeric(df$down.norm),type=ifelse(df$dataset %in% betacoronas,'Coronavirus','Other'))

ggboxplot(data = df2,x = 'type',y = 'deplete.score',palette = 'npg',fill = 'type',add='jitter',shape='type')+
stat_compare_means(aes(group = type),vjust=2)

wilcox.test(as.numeric(df$down.norm[df$dataset %in% betacoronas]),as.numeric(df$down.norm[!df$dataset %in% betacoronas]),paired = FALSE)

########
rna.binding.enriched=c()

for (dataset in c("mason_latest",
                          "SRP040070_3","SRP040070_7","SRP040070_9",
                          "SRP227272_38",'SRP279203_72','SRP294125_74',"SRP078309_53","SRP178454_50","SRP186406_51","SRP216763_55","SRP222569_54","SRP251704_52",
                          "SRP273785_56",'SRP284977_76','SRP284977_77'))
{   
  res=read.table(paste0('GO enrichment covid19/table-',dataset,'_ds-Term-For-Term-Benjamini-Hochberg.txt'),header=TRUE)
  
  rna.binding.enriched=c(rna.binding.enriched,'RNA binding' %in% res$name[res$p.adjusted<=0.05])
  
  names(rna.binding.enriched)[length(rna.binding.enriched)]=dataset
}

betacoronas=c("mason_latest","SRP040070_3","SRP040070_7","SRP040070_9","SRP227272_38",'SRP279203_72','SRP294125_74','SRP284977_76','SRP284977_77')

table(rna.binding.enriched[names(rna.binding.enriched) %in% betacoronas])

table(rna.binding.enriched[!names(rna.binding.enriched) %in% betacoronas])


#####

rna.binding.enriched=c()

for (dataset in c("mason_latest",
                  "SRP040070_3","SRP040070_7","SRP040070_9",
                  "SRP227272_38",'SRP279203_72','SRP294125_74',"SRP078309_53","SRP178454_50","SRP186406_51","SRP216763_55","SRP222569_54","SRP251704_52",
                  "SRP273785_56",'SRP284977_76','SRP284977_77'))
{   
  res=read.table(paste0('GO enrichment covid19/table-',dataset,'_de-Term-For-Term-Benjamini-Hochberg.txt'),header=TRUE)
  
  rna.binding.enriched=c(rna.binding.enriched,'RNA binding' %in% res$name[res$p.adjusted<=0.05])
  
  names(rna.binding.enriched)[length(rna.binding.enriched)]=dataset
}

betacoronas=c("mason_latest","SRP040070_3","SRP040070_7","SRP040070_9","SRP227272_38",'SRP279203_72','SRP294125_74','SRP284977_76','SRP284977_77')

table(rna.binding.enriched[names(rna.binding.enriched) %in% betacoronas])

table(rna.binding.enriched[!names(rna.binding.enriched) %in% betacoronas])

